services:
  streamlit-ui:
    build: ./streamlit-ui
    ports:
      - "8501:8501"
    volumes:
      - ./temp:/app/temp
    depends_on:
      - cv-optimizer-api
      - docx-injector

  cv-optimizer-api:
    build: ./cv-optimizer-api
    ports:
      - "5000:5000"
    volumes:
      - ./temp:/app/temp
    env_file:
      - .env

  docx-injector:
    build: ./docx-injector
    ports:
      - "6000:8080"
    volumes:
      - ./temp:/app/temp